#pragma once
#include "CoreMinimal.h"
#include "GameFramework/Character.h"
#include "Engine/NetSerialization.h"
#include "MCDataAssets.h"
#include "MCToothCharacter.generated.h"
class UCameraComponent;
class USpringArmComponent;
class UInputAction;
class UInputMappingContext;
class UMCToothPhysicsComponent;
class UPhysicsControlComponent;
class UMCToothStatusComponent;
class UMCGazeComponent;
class UMCGripComponent;
class UMCExpressionComponent;
class AMCFoodActor;
class AMCArenaTooth;
class AMCRewardChest;
class UMaterialInstanceDynamic;
class UMeshComponent;
class UEnhancedInputLocalPlayerSubsystem;
struct FInputActionValue;

UCLASS(Blueprintable)
class MESSCONTROL_API AMCToothCharacter : public ACharacter
{
    GENERATED_BODY()
    friend void MCTickApprovalValidation(UWorld* World);
#if !UE_BUILD_SHIPPING
    friend void MCTickClimbNetworkValidation(UWorld* World);
    friend void MCTickSprayNetworkValidation(UWorld* World);
    friend void MCTickDashSuctionValidation(UWorld* World);
#endif
public:
    AMCToothCharacter(const FObjectInitializer& ObjectInitializer=FObjectInitializer::Get());
    virtual void OnConstruction(const FTransform& Transform) override;
    virtual void PostInitializeComponents() override;
    virtual void Tick(float DeltaSeconds) override;
    virtual void SetupPlayerInputComponent(UInputComponent* PlayerInputComponent) override;
    virtual void PawnClientRestart() override;
    virtual void PossessedBy(AController* NewController) override;
    virtual void Landed(const FHitResult& Hit) override;
    virtual void FellOutOfWorld(const UDamageType& DamageType) override;
    virtual void EndPlay(const EEndPlayReason::Type Reason) override;
    virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Physics") TObjectPtr<UMCToothPhysicsComponent> ToothPhysics;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Care") TObjectPtr<UMCToothStatusComponent> Status;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Care") TObjectPtr<class UMCBrushContactComponent> BrushContact;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Gaze") TObjectPtr<UMCGazeComponent> Gaze;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Grip") TObjectPtr<UMCGripComponent> Grip;
    UPROPERTY(VisibleAnywhere,BlueprintReadOnly,Category="Food") TObjectPtr<class UMCFoodCollectionComponent> FoodCollection;
    UPROPERTY(ReplicatedUsing=OnRep_Yawn,BlueprintReadOnly,Category="Yawn") double YawnEndsAt=0;
    UPROPERTY(Replicated,BlueprintReadOnly,Category="Yawn") TObjectPtr<class AMCTongue> YawnTongue;
    UPROPERTY(Replicated,BlueprintReadOnly,Category="Yawn") FVector YawnAnchor=FVector::ZeroVector;
    UPROPERTY(Replicated,BlueprintReadOnly,Category="Yawn") double YawnStartedAt=-100;
    UPROPERTY(Replicated,BlueprintReadOnly,Category="Yawn") FVector YawnPullDirection=FVector::ForwardVector;
    float YawnPoseAlpha() const;
    FVector YawnHandPoint(int32 Side) const;
    bool IsYawning() const;
    void BeginYawn(class AMCTongue* Tongue,float Seconds);
    void UpdateYawn(float Dt);
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Emotes") TObjectPtr<UMCExpressionComponent> Expression;
    UPROPERTY(Replicated, BlueprintReadOnly, Category="Care") bool bSelfCare=false;
    UPROPERTY(Replicated, BlueprintReadOnly, Category="Care") TObjectPtr<AActor> CareTarget;
    UPROPERTY(Replicated, BlueprintReadOnly, Category="Care") float ContactProgress=0;
    UPROPERTY(Replicated, BlueprintReadOnly, Category="Food") TObjectPtr<AMCFoodActor> HeldFood;
    UPROPERTY(Replicated, BlueprintReadOnly, Category="Tools") TObjectPtr<AMCFoodActor> EquippedBrush;
    UPROPERTY(Replicated, BlueprintReadOnly, Category="Coffee") bool bInCoffee=false;
    UPROPERTY(Replicated, BlueprintReadOnly, Category="Coffee") TObjectPtr<AMCArenaTooth> ClingTooth;
    bool bWantsCling=false;
    FVector ClingPoint=FVector::ZeroVector;
    FVector2D PaddleInput=FVector2D::ZeroVector;
    UPROPERTY(Replicated,BlueprintReadOnly,Category="Swimming") FVector_NetQuantizeNormal SwimIntent=FVector::ZeroVector;
    bool HasBrush() const;
    UPROPERTY(VisibleAnywhere,BlueprintReadOnly,Category="Tools") TObjectPtr<class UMCInventoryComponent> Inventory;
    UPROPERTY(Replicated,BlueprintReadOnly,Category="Feedback") double TaskSuccessAt=-100;
    UPROPERTY(Replicated,BlueprintReadOnly,Category="Feedback") double TaskFailureAt=-100;
    void NotifyTaskFeedback(bool Success,FVector Point=FVector::ZeroVector);
    bool CanSwitchTool() const;
    UFUNCTION(BlueprintCallable, Category="Tools") void ThrowItem();
    UFUNCTION(Server,Reliable) void ServerThrowItem();
    UFUNCTION(Server,Unreliable) void ServerPaddle(FVector2D Direction);
    UPROPERTY(Replicated, BlueprintReadOnly, Category="Life") double RespawnAt=0;
    UPROPERTY(Replicated, BlueprintReadOnly, Category="Life") int32 RespawnSourceId=0;
    bool CanWork() const;
    UPROPERTY(Replicated,BlueprintReadOnly,Category="Rewards") TObjectPtr<AMCRewardChest> RewardInteraction;
    UFUNCTION(Server,Reliable) void ServerBeginRewardOpening(AMCRewardChest* Chest);
    bool IsPrimaryHeld() const { return bPrimaryHeld; }
    UPROPERTY(ReplicatedUsing=OnRep_ThroatCapture,BlueprintReadOnly,Category="Throat") TObjectPtr<class AMCThroat> SwallowedBy;
    UPROPERTY(Replicated) FVector ThroatCaptureStart=FVector::ZeroVector;
    UPROPERTY(Replicated) TObjectPtr<class AMCThroat> OrderJumpTarget;
    UPROPERTY(Replicated) double OrderJumpStartedAt=-100;
    UPROPERTY(Replicated) bool bOrderJumpLaunched=false;
    static constexpr float OrderPrepareSeconds=.34f;
    void ClearOrderJump();
    UFUNCTION(Server,Reliable) void ServerOrderJump(class AMCThroat* Throat);
    UFUNCTION(Client,Reliable) void ClientOrderLaunch(FVector Velocity);
    UFUNCTION(Client,Reliable) void ClientUvulaHop(FVector Velocity);
    UFUNCTION(Client,Reliable) void ClientThroatExit(FVector Location,FVector Velocity);
    void SetThroatCapture(class AMCThroat* Throat);
    void StatusChanged();
    void DropFood();
    void CancelGameplayInput();
    // Retained for saved Blueprint compatibility; Shift now acts on press.
    UPROPERTY(meta=(DeprecatedProperty,DeprecationMessage="Sprint and dash now start on Shift press.")) float SprintHoldSeconds=.18f;
    UFUNCTION(BlueprintPure,Category="Locomotion|Dash") bool IsDashing() const;
    UFUNCTION(BlueprintPure,Category="Locomotion|Dash") float GetDashProgress() const;
    UFUNCTION(BlueprintPure,Category="Locomotion|Dash") FVector GetDashDirection() const;
    UFUNCTION(BlueprintPure,Category="Locomotion|Dash") float GetDashDuration() const;
    UFUNCTION(BlueprintCallable,Category="Locomotion|Dash") void SetSprintInputHeld(bool Held);
    UFUNCTION(Server,Reliable) void ServerSetPrimary(bool bActive);
    bool CanContact(AActor* Target) const;
    void UpdateMouthCamera(float Dt);
    UFUNCTION(BlueprintCallable,Category="Camera") void ApplyCameraOrbitInput(FVector2D Delta);
    UFUNCTION(BlueprintCallable,Category="Camera") void ZoomCamera(float ScrollDelta);
    FVector CameraMoveDirection(bool Right) const;
    void UpdateCameraWallReveal(float Dt,const FVector& Eye,const FVector& Focus);
    void ClearCameraWallReveal();
    UMCToothStatusComponent* FindCareTarget(bool bBrush) const;
    void AdvanceCare(float Dt);
    void ResetContact();
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Physics") TObjectPtr<UPhysicsControlComponent> Muscles;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Visuals") TObjectPtr<USceneComponent> BrushPivot;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Visuals") TObjectPtr<UStaticMeshComponent> Brush;
    UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category="Visuals") TObjectPtr<UMCPlayerAppearance> Appearance;
    UPROPERTY(ReplicatedUsing=OnRep_BagColor, BlueprintReadOnly, Category="Visuals") FLinearColor BagColor=FLinearColor::White;
    UFUNCTION(BlueprintPure, Category="Visuals") FLinearColor GetPlayerColor() const { return BagColor; }
    void ApplyPlayerColor(FLinearColor Color);
    UFUNCTION(BlueprintPure, Category="Locomotion|Stamina") float GetStamina() const;
    UFUNCTION(BlueprintPure, Category="Locomotion|Stamina") float GetMaxStamina() const;
    UFUNCTION(BlueprintPure, Category="Locomotion|Stamina") float GetStaminaNormalized() const;
    UFUNCTION(BlueprintPure, Category="Locomotion|Stamina") bool IsStaminaExhausted() const;
    bool FindPlayerBrushContact(const AMCToothCharacter* Worker,FVector& Point,FVector& Normal) const;
    FName RigBone(FName BoneRole) const;
    FTransform StandingMeshTransform() const;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Camera") TObjectPtr<USpringArmComponent> CameraBoom;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Camera") TObjectPtr<UCameraComponent> Camera;
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="UI") TObjectPtr<class UMCPlayerNameComponent> PlayerNameLabel;
    UPROPERTY(EditAnywhere,BlueprintReadWrite,Category="Camera|Mouth",meta=(ClampMin="400",ClampMax="1600")) float FollowDistance=900;
    UPROPERTY(EditAnywhere,BlueprintReadWrite,Category="Camera|Mouth",meta=(ClampMin="150",ClampMax="700")) float FollowHeight=500;
    UPROPERTY(EditAnywhere,BlueprintReadWrite,Category="Camera|Mouth",meta=(ClampMin="45",ClampMax="95")) float FollowFOV=55;
    UPROPERTY(EditAnywhere,BlueprintReadWrite,Category="Camera|Mouth",meta=(ToolTip="Camera aim offset in centimetres from the tracked point; negative Z reveals the front teeth.")) FVector CameraFocusOffset=FVector(80,0,-140);
    UPROPERTY(EditAnywhere,BlueprintReadWrite,Category="Camera|Mouth",meta=(ClampMin="1",ClampMax="20")) float FollowSpeed=7;
    UPROPERTY(EditAnywhere,BlueprintReadWrite,Category="Camera|Mouth",meta=(ToolTip="Movement in centimetres allowed around the tracked point before the camera follows.")) FVector CameraDeadZone=FVector(110,80,90);
    UPROPERTY(EditAnywhere,BlueprintReadWrite,Category="Camera|Orbit",meta=(ClampMin="0.02",ClampMax="1")) float CameraOrbitSensitivity=.18f;
    UPROPERTY(EditAnywhere,BlueprintReadWrite,Category="Camera|Orbit",meta=(ClampMin="10",ClampMax="300")) float CameraZoomStep=100.f;
    UPROPERTY(EditAnywhere,BlueprintReadWrite,Category="Camera|Walls") bool bCameraWallReveal=true;
    UPROPERTY(EditAnywhere,BlueprintReadWrite,Category="Camera|Walls",meta=(ClampMin="60",ClampMax="500")) float CameraWallRevealRadius=500.f;
    UPROPERTY(EditAnywhere,BlueprintReadWrite,Category="Camera|Walls",meta=(ClampMin="0.02",ClampMax="0.8")) float CameraWallRevealFeather=.25f;
    bool bManualCameraOrbit=false;
    float CameraOrbitYaw=0,CameraOrbitPitch=-30,CameraOrbitDistance=1000;
    bool bMouthCameraInitialized=false;
    bool bMouthCameraHeld=false;
    FVector MouthCameraFocus=FVector::ZeroVector, MouthCameraEye=FVector::ZeroVector;
    TWeakObjectPtr<AActor> MouthCameraBounds;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Animation") TObjectPtr<UMCAnimationProfile> AnimationProfile;
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Audio") TObjectPtr<UMCSoundPalette> SoundPalette;
    UPROPERTY(BlueprintReadWrite, Category="Animation") FMCAnimationSettings AnimationSettings;
    UPROPERTY(BlueprintReadWrite, Category="Animation") bool bPreviewAnimation = false;
    UPROPERTY(ReplicatedUsing=OnRep_Working, BlueprintReadOnly, Category="Action") bool bBrushing = false;
    UPROPERTY(ReplicatedUsing=OnRep_Working, BlueprintReadOnly, Category="Action") bool bHandling = false;
    UFUNCTION(BlueprintCallable, Category="Animation") void SaveTuning();
    UFUNCTION(BlueprintCallable, Category="Animation") void ResetTuning();
    UFUNCTION(BlueprintCallable, Category="Action") void SwingBrush();
    UFUNCTION(BlueprintCallable, Category="Physics") void SpawnPracticeTooth();
    float AnimationGait=0.f, AnimationSpeed=0.f, AnimationBob=0.f, AnimationPitch=0.f, AnimationBrushAngle=0.f;
    float AnimationSwim=0,AnimationStroke=0,AnimationSwimEffort=0,AnimationTurn=0,AnimationBrake=0;
    float AnimationRun=0,AnimationSticky=0,AnimationSlip=0,AnimationEffort=0,AnimationStance=.6f;
    float AnimationAir=0,AnimationLanding=0;
    float AnimationClimb=0,AnimationClimbPhase=0;
    float AnimationOrderPrepare=0,AnimationOrderFlight=0,AnimationOrderPress=0;
    FVector AnimationDirection=FVector::ForwardVector;
    FVector AnimationInertia=FVector::ZeroVector;
    FVector AnimationToolOffset=FVector::ZeroVector;
    int32 ValidatedSwingCount=0, ConfirmedHitCount=0;
    int32 SuccessfulBrushContacts=0;
protected:
    virtual void BeginPlay() override;
private:
    friend class UMCValidationSubsystem;
    friend class AMCCoreScenario;
    friend class AMCDayOneScenario;
    void BuildInput();
    void ApplyAppearance();
    void MoveForward(const FInputActionValue& Value);
    void MoveRight(const FInputActionValue& Value);
    void OrbitMouseX(const FInputActionValue& Value);
    void OrbitMouseY(const FInputActionValue& Value);
    void CameraMouseWheel(const FInputActionValue& Value);
    void InitializeCameraOrbit();
    FVector2D WorldPaddleInput() const;
    void StartJump(); void StopJump();
    void StartSprint(); void StopSprint();
    void CancelSprintInput();
    bool bSprintInputHeld=false;
    void UpdateLocomotion(float Dt);
    void StartBrush(); void StopBrush(); void StartHandle(); void StopHandle();
    void StartPrimary(); void StopPrimary();
    UFUNCTION(Server,Reliable) void ServerToggleFoodCollection();
    void SelectBrush(); void SelectPickaxe(); void SelectKnife(); void SelectSpray();
    void ResolvePrimaryAction();
    void TogglePanel(); void ToggleConnection(); void RestartRun();
    UFUNCTION(Server, Reliable) void ServerSetWorking(bool bBrush, bool bActive);
    void ToggleSelfCare();
    UFUNCTION(Server, Reliable) void ServerToggleSelfCare();
    UFUNCTION() void OnRep_Working();
    UFUNCTION() void OnRep_BagColor();
    UFUNCTION() void OnRep_Yawn();
    UFUNCTION() void OnRep_ThroatCapture();
    float OrderJumpAirControl=.05f;
    bool bThroatCaptured=false;
    TWeakObjectPtr<class AMCThroat> ThroatTickPrerequisite;
    TArray<TWeakObjectPtr<AActor>> OrderJumpIgnoredActors;
    void FindWork(float DeltaSeconds);
    UFUNCTION(Server,Reliable) void ServerSwingBrush();
    UFUNCTION(NetMulticast,Reliable) void MulticastSwing();
    UFUNCTION(NetMulticast,Unreliable) void MulticastHitSound(FVector Location);
    UFUNCTION() void OnBodyHit(UPrimitiveComponent* HitComponent,AActor* OtherActor,UPrimitiveComponent* OtherComponent,FVector NormalImpulse,const FHitResult& Hit);
    void ResolveSwing();
    UPROPERTY() TObjectPtr<UInputMappingContext> InputMap;
    UPROPERTY() TWeakObjectPtr<UEnhancedInputLocalPlayerSubsystem> AppliedInputSubsystem;
    UPROPERTY() TObjectPtr<UInputAction> ForwardAction;
    UPROPERTY() TObjectPtr<UInputAction> RightAction;
    UPROPERTY() TObjectPtr<UInputAction> JumpAction;
    UPROPERTY() TObjectPtr<UInputAction> SprintAction;
    UPROPERTY() TObjectPtr<UInputAction> BrushAction;
    UPROPERTY() TObjectPtr<UInputAction> HandleAction;
    UPROPERTY() TObjectPtr<UInputAction> PanelAction;
    UPROPERTY() TObjectPtr<UInputAction> ConnectionAction;
    UPROPERTY() TObjectPtr<UInputAction> RestartAction;
    UPROPERTY() TObjectPtr<UInputAction> SwingAction;
    UPROPERTY() TObjectPtr<UInputAction> OrbitXAction;
    UPROPERTY() TObjectPtr<UInputAction> OrbitYAction;
    UPROPERTY() TObjectPtr<UInputAction> ZoomAction;
    UPROPERTY() TObjectPtr<UInputAction> SelfCareAction;
    UPROPERTY() TObjectPtr<UInputAction> ThrowAction;
    UPROPERTY() TArray<TObjectPtr<UInputAction>> ToolActions;
    UPROPERTY() TObjectPtr<UMaterialInstanceDynamic> StatusMaterial;
    UPROPERTY() TArray<TObjectPtr<UMaterialInstanceDynamic>> FaceMaterials;
    UPROPERTY() TObjectPtr<UMaterialInstanceDynamic> BagMaterial;
    UPROPERTY() TObjectPtr<AMCToothCharacter> PracticeTooth;
    float NextSwingTime=0.f;
    float SwingStartedAt=-10.f;
    float SwingContactEndsAt=0.f;
    float LastEnvironmentHit=-10.f;
    FTimerHandle SwingTimer;
    float Gait = 0.f;
    float LandingImpulse = 0.f;
    float WorkStartedAt = -10.f;
    float SoundAccumulator = 0.f;
    float BrushAngle = 0.f;
    bool bLoadedLocalTuning = false;
    bool bDeathReported=false;
    bool bLastContactBrush=false;
    UPROPERTY(Replicated) bool bPrimaryHeld=false;
    float ContactElapsed=0;
    FVector2D LocalPaddle=FVector2D::ZeroVector;
    float PaddleSendElapsed=0;
    float PreviousAnimationYaw=0,PreviousAnimationSpeed=0;
    FVector PreviousLocomotionVelocity=FVector::ZeroVector;
    double LastPaddleAt=0;
    float CameraOrbitViewDistance=1000.f;
    FRotator CameraOrbitViewRotation=FRotator::ZeroRotator;
    struct FCameraWallState { ECollisionResponse CameraResponse=ECR_Block; float Amount=0; };
    TMap<TWeakObjectPtr<UMeshComponent>,FCameraWallState> CameraRevealWalls;
    double NextCameraWallScan=0;
};
