(fn ConstructionScript ()
  (bind master (Math|Float|Clamp(Float) :Value (Variables|RewardGlow|GetGlowStrength) :Min 0 :Max 10))
  (bind speed (Math|Float|Clamp(Float) :Value (Variables|RewardGlow|GetGlowAnimationSpeed) :Min 0 :Max 10))
  (bind tint (Variables|RewardGlow|GetGlowTint))
  (bind actorScale (Transformation|GetActorScale3D))
  (bind scale (/ (+ (+ (.x actorScale) (.y actorScale)) (.z actorScale)) 3))
  (bind rays (Variables|Default|GetRewardGlowRays))
  (bind raysStrength (* master (Math|Float|Clamp(Float) :Value (Variables|RewardGlow|GetRaysStrength) :Min 0 :Max 10)))
  (Components|StaticMesh|SetStaticMesh :self rays :NewMesh "/Game/Gameplay/VFX/RewardChest/SM_RewardChest_RadianceDisk.SM_RewardChest_RadianceDisk")
  (Rendering|Material|SetMaterial :self rays :ElementIndex 0 :Material "/Game/Gameplay/VFX/RewardChest/M_RewardChest_RaysFast.M_RewardChest_RaysFast")
  (Transformation|SetRelativeLocation :self rays :NewLocation (Math|Vector|MakeVector :X 0 :Y 0 :Z 75))
  (Rendering|SetCastShadow :self rays :NewCastShadow false)
  (Collision|SetCollisionEnabled :self rays :NewType "NoCollision")
  (Rendering|Material|SetScalarParameterValueOnMaterials :self rays :ParameterName "GlowIntensity" :ParameterValue raysStrength)
  (Rendering|Material|SetScalarParameterValueOnMaterials :self rays :ParameterName "AnimationSpeed" :ParameterValue speed)
  (Rendering|Material|SetScalarParameterValueOnMaterials :self rays :ParameterName "EffectScale" :ParameterValue scale)
  (Rendering|Material|SetColorParameterValueOnMaterials :self rays :ParameterName "GlowColor" :ParameterValue tint)
  (Rendering|SetVisibility :self rays :bNewVisibility (> raysStrength 0) :bPropagateToChildren false)
  (bind beam (Variables|Default|GetRewardSpotlightBeam))
  (bind beamStrength (* master (Math|Float|Clamp(Float) :Value (Variables|RewardGlow|GetSpotlightGlowStrength) :Min 0 :Max 10)))
  (Components|StaticMesh|SetStaticMesh :self beam :NewMesh "/Game/Gameplay/VFX/RewardChest/SM_RewardChest_SingleBeam.SM_RewardChest_SingleBeam")
  (Rendering|Material|SetMaterial :self beam :ElementIndex 0 :Material "/Game/Gameplay/VFX/RewardChest/M_RewardChest_BeamFast.M_RewardChest_BeamFast")
  (Transformation|SetRelativeLocation :self beam :NewLocation (Math|Vector|MakeVector :X 0 :Y 0 :Z 0))
  (Rendering|SetCastShadow :self beam :NewCastShadow false)
  (Collision|SetCollisionEnabled :self beam :NewType "NoCollision")
  (Rendering|Material|SetScalarParameterValueOnMaterials :self beam :ParameterName "GlowIntensity" :ParameterValue beamStrength)
  (Rendering|Material|SetScalarParameterValueOnMaterials :self beam :ParameterName "AnimationSpeed" :ParameterValue speed)
  (Rendering|Material|SetScalarParameterValueOnMaterials :self beam :ParameterName "EffectScale" :ParameterValue scale)
  (Rendering|Material|SetColorParameterValueOnMaterials :self beam :ParameterName "GlowColor" :ParameterValue tint)
  (Rendering|SetVisibility :self beam :bNewVisibility (> beamStrength 0) :bPropagateToChildren false)
  (bind sparks (Variables|Default|GetRewardMagicSparks))
  (bind sparksStrength (* master (Math|Float|Clamp(Float) :Value (Variables|RewardGlow|GetSparksStrength) :Min 0 :Max 10)))
  (Components|StaticMesh|SetStaticMesh :self sparks :NewMesh "/Game/Gameplay/VFX/RewardChest/SM_RewardChest_SparksLite.SM_RewardChest_SparksLite")
  (Rendering|Material|SetMaterial :self sparks :ElementIndex 0 :Material "/Game/Gameplay/VFX/RewardChest/M_RewardChest_SparksFast.M_RewardChest_SparksFast")
  (Transformation|SetRelativeLocation :self sparks :NewLocation (Math|Vector|MakeVector :X 0 :Y 0 :Z 70))
  (Rendering|SetCastShadow :self sparks :NewCastShadow false)
  (Collision|SetCollisionEnabled :self sparks :NewType "NoCollision")
  (Rendering|Material|SetScalarParameterValueOnMaterials :self sparks :ParameterName "GlowIntensity" :ParameterValue sparksStrength)
  (Rendering|Material|SetScalarParameterValueOnMaterials :self sparks :ParameterName "AnimationSpeed" :ParameterValue speed)
  (Rendering|Material|SetScalarParameterValueOnMaterials :self sparks :ParameterName "EffectScale" :ParameterValue scale)
  (Rendering|Material|SetColorParameterValueOnMaterials :self sparks :ParameterName "GlowColor" :ParameterValue tint)
  (Rendering|SetVisibility :self sparks :bNewVisibility (> sparksStrength 0) :bPropagateToChildren false)
  (bind seam (Variables|Default|GetRewardSeamLight))
  (bind seamStrength (* master (Math|Float|Clamp(Float) :Value (Variables|RewardGlow|GetSeamGlowStrength) :Min 0 :Max 10)))
  (Components|StaticMesh|SetStaticMesh :self seam :NewMesh "/Game/Gameplay/VFX/RewardChest/SM_RewardChest_SeamContour.SM_RewardChest_SeamContour")
  (Rendering|Material|SetMaterial :self seam :ElementIndex 0 :Material "/Game/Gameplay/VFX/RewardChest/M_RewardChest_SeamFast.M_RewardChest_SeamFast")
  (Transformation|SetRelativeLocation :self seam :NewLocation (Math|Vector|MakeVector :X 0 :Y 0 :Z 0))
  (Rendering|SetCastShadow :self seam :NewCastShadow false)
  (Collision|SetCollisionEnabled :self seam :NewType "NoCollision")
  (Rendering|Material|SetScalarParameterValueOnMaterials :self seam :ParameterName "GlowIntensity" :ParameterValue seamStrength)
  (Rendering|Material|SetScalarParameterValueOnMaterials :self seam :ParameterName "AnimationSpeed" :ParameterValue speed)
  (Rendering|Material|SetScalarParameterValueOnMaterials :self seam :ParameterName "EffectScale" :ParameterValue scale)
  (Rendering|Material|SetColorParameterValueOnMaterials :self seam :ParameterName "GlowColor" :ParameterValue tint)
  (Rendering|SetVisibility :self seam :bNewVisibility (> seamStrength 0) :bPropagateToChildren false)
  (bind floor (Variables|Default|GetRewardFloorHalo))
  (bind floorStrength (* master (Math|Float|Clamp(Float) :Value (Variables|RewardGlow|GetFloorGlowStrength) :Min 0 :Max 10)))
  (Components|StaticMesh|SetStaticMesh :self floor :NewMesh "/Game/Gameplay/VFX/RewardChest/SM_RewardChest_Halo.SM_RewardChest_Halo")
  (Rendering|Material|SetMaterial :self floor :ElementIndex 0 :Material "/Game/Gameplay/VFX/RewardChest/M_RewardChest_FloorFast.M_RewardChest_FloorFast")
  (Transformation|SetRelativeLocation :self floor :NewLocation (Math|Vector|MakeVector :X 0 :Y 0 :Z 0))
  (Rendering|SetCastShadow :self floor :NewCastShadow false)
  (Collision|SetCollisionEnabled :self floor :NewType "NoCollision")
  (Rendering|Material|SetScalarParameterValueOnMaterials :self floor :ParameterName "GlowIntensity" :ParameterValue floorStrength)
  (Rendering|Material|SetScalarParameterValueOnMaterials :self floor :ParameterName "AnimationSpeed" :ParameterValue speed)
  (Rendering|Material|SetScalarParameterValueOnMaterials :self floor :ParameterName "EffectScale" :ParameterValue scale)
  (Rendering|Material|SetColorParameterValueOnMaterials :self floor :ParameterName "GlowColor" :ParameterValue tint)
  (Rendering|SetVisibility :self floor :bNewVisibility (> floorStrength 0) :bPropagateToChildren false)
  (bind inner (Variables|Default|GetRewardInnerGlow))
  (bind innerPower (* master (Math|Float|Clamp(Float) :Value (Variables|RewardGlow|GetInnerLightIntensity) :Min 0 :Max 10000)))
  (Transformation|SetRelativeLocation :self inner :NewLocation (Math|Vector|MakeVector :X 0 :Y 0 :Z 95))
  (Rendering|Components|Light|SetIntensityUnits :self inner :NewIntensityUnits "Lumens")
  (Rendering|Components|Light|SetIntensity :self inner :NewIntensity innerPower)
  (Rendering|Lighting|SetAttenuationRadius :self inner :NewRadius 220)
  (Rendering|Components|Light|SetCastShadows :self inner :bNewValue false)
  (Rendering|Components|Light|SetMaxDrawDistance :self inner :NewValue 3000)
  (Rendering|SetVisibility :self inner :bNewVisibility (> innerPower 0) :bPropagateToChildren false)
  (bind spot (Variables|Default|GetRewardOverheadSpot))
  (bind spotPower (* master (Math|Float|Clamp(Float) :Value (Variables|RewardGlow|GetOverheadLightIntensity) :Min 0 :Max 10000)))
  (Transformation|SetRelativeLocation :self spot :NewLocation (Math|Vector|MakeVector :X 0 :Y 0 :Z 420))
  (Rendering|Components|Light|SetIntensityUnits :self spot :NewIntensityUnits "Lumens")
  (Rendering|Components|Light|SetIntensity :self spot :NewIntensity spotPower)
  (Rendering|Lighting|SetAttenuationRadius :self spot :NewRadius 700)
  (Rendering|Components|Light|SetCastShadows :self spot :bNewValue false)
  (Rendering|Components|Light|SetMaxDrawDistance :self spot :NewValue 3000)
  (Rendering|SetVisibility :self spot :bNewVisibility (> spotPower 0) :bPropagateToChildren false)
  (Transformation|SetRelativeRotation :self spot :NewRotation (Math|Rotator|MakeRotator :Pitch -90 :Yaw 0 :Roll 0))
  (Rendering|Lighting|SetInnerConeAngle :self spot :NewInnerConeAngle 12)
  (Rendering|Lighting|SetOuterConeAngle :self spot :NewOuterConeAngle 23)
  (Rendering|Material|SetMaterial :self (Variables|MCRewardChest|GetBody) :ElementIndex 0 :Material "/Game/Art/Materials/Buster/MI_Chest.MI_Chest")
  (Rendering|Material|SetMaterial :self (Variables|MCRewardChest|GetLid) :ElementIndex 0 :Material "/Game/Art/Materials/Buster/MI_Chest.MI_Chest")
)